### PR TITLE
Remove jQuery

### LINKED ISSUE #1: Remove jquery
Currently jQuery is being used just to add html to a specific div, which can be done by vanilla JavaScript.
Removing jQuery will reduce the extension size.

### PR DESCRIPTION
**Pull request by vladimyr**
Closes #1 😉 See a80eaea for details.

### CODE REVIEW

**Comment by vladimyr** [comment]
Sure, but may I ask why? 😕

**Comment by prabhakar267** [comment]
@vladimyr  Editor configs are specific to each user, you don't want to enforce your configuration on others.
I might be using a different editor all together

**Comment by vladimyr** [comment]
> Editor configs are specific to each user

Let's use tabs vs spaces debate as example. User A has indent using spaces option checked while user B has indent using tabs options set. If they work together on same codebase sooner or later you'll end up with chaotic mix of tabs and spaces all across your code. That is why you have project specific editor configs which are enforced on all devs but only inside given workspace with rules defined by lead dev: you or in this case suggested by me :bowtie: 

> I might be using a different editor all together

It is completely irrelevant which editor you use most of them already have native support for `.editorconfig` driven configuration: https://editorconfig.org/#download

Let me summarize it once again; `.editorconfig`:
- does not affect global editor settings set by user
- dose not affect other projects apart from one it is contained by
- enforces consistent editing settings inside corresponding project
- is plugin-free/standard mechanism of maintaining consistent editing style between different editors & IDEs   

Furthermore you'll have really hard time finding any recent and popular software project that does not use it because it has virtually zero flaws:
- react's [`.editorconfig`](https://github.com/facebook/react/blob/36c5d69caa3e9270b1b175b33cd8c53cc6c0e690/.editorconfig)
- vue's [`.editorconfig`](https://github.com/vuejs/vue/blob/9d19f84d4e7a281484a6eb3f92e6a266a1adc243/.editorconfig)
- angular's [`.editorconfig`](https://github.com/angular/angular/blob/cb59d8748907c62cdf6ff5f1aff65fdef62bba28/.editorconfig)
- jQuery's [`.editorconfig`](https://github.com/jquery/jquery/blob/dae5f3ce3d2df27873d01f0d9682f6a91ad66b87/.editorconfig)
- Django's [`.editorconfig`](https://github.com/django/django/blob/d093e01ec05f661063507503fdf294eb6ee54dee/.editorconfig)
- Ruby's [`.editorconfig`](https://github.com/ruby/ruby/blob/d4b0efc010a45e904ecdad2dd74374b5c74e61e3/.editorconfig)
- legacy list of all _users_: https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig

Don't get me wrong I'm not some kind of _editorconfig warrior_ :upside_down_face: did this little essay just to clarify your misconceptions about it. If you still don't want it I'll remove it but give it a shot money back is guaranteed :grin:

**Comment by vladimyr** [comment]
**PS** Aside from editing conventions it is also useful for preventing those type of errors [`insert_final_newline`](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#insert_final_newline): https://github.com/prabhakar267/github-email-extractor/pull/6/files#diff-93cbdb4abe59691b1fbc69171be038d6L4

**Comment by prabhakar267** [comment]
@vladimyr That was too strong a point to be ignored!
Point taken!

**Pull request merged**
